# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aN3KJgrQodm0wd92lNR-zGJQLXhnAs6r
"""

!pip install yfinance vaderSentiment

import yfinance as yf
import pandas as pd
import requests
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# 1. FETCH MARKET DATA (Price & Volume)
def get_market_data(ticker="ETH-USD"):
    data = yf.download(ticker, start="2023-01-01", interval="1d")
    data['Returns'] = data['Close'].pct_change()
    return data

# 2. FETCH SENTIMENT DATA (Simulated via News API)
# In production, use NewsAPI.org or CryptoPanic API
def get_sentiment_score(text_list):
    analyzer = SentimentIntensityAnalyzer()
    scores = [analyzer.polarity_scores(text)['compound'] for text in text_list]
    return sum(scores) / len(scores) if scores else 0

# 3. MOCK DATA MERGING (For demonstration)
# Replace these with real API calls to Etherscan (On-Chain) and NewsAPI (Sentiment)
def prepare_full_dataset():
    df = get_market_data()

    # Simulate On-Chain: High gas usage or whale moves often precede volatility
    df['Gas_Fees'] = [15 + (i % 10) for i in range(len(df))]

    # Simulate Sentiment: Random scores between -1 (bearish) and 1 (bullish)
    # Use real scrapers here for a production bot
    df['Sentiment'] = [0.1 * (i % 5) - 0.2 for i in range(len(df))]

    # Create target: Predict next day's Close price
    df['Target'] = df['Close'].shift(-1)
    return df.dropna()

# 4. TRAIN THE MODEL
data = prepare_full_dataset()
features = ['Close', 'Volume', 'Returns', 'Gas_Fees', 'Sentiment']
X = data[features]
y = data['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. PREDICT
last_row = X.tail(1)
prediction = model.predict(last_row)
print(f"Predicted ETH Price for Tomorrow: ${prediction[0]:.2f}")

!pip install newsapi-python

import yfinance as yf
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from newsapi import NewsApiClient
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# 1. Fetch Hourly ETH-EUR Data
# Note: yfinance allows '1h' interval for up to 730 days
eth_data = yf.download('ETH-EUR', period='1mo', interval='1h')

# 2. Add Sentiment Feature (Simplified for Hourly)
def get_hourly_sentiment(api_key):
    newsapi = NewsApiClient(api_key=api_key)
    # Fetch recent ETH headlines
    articles = newsapi.get_everything(q='Ethereum', language='en', sort_by='publishedAt', page_size=20)
    analyzer = SentimentIntensityAnalyzer()
    scores = [analyzer.polarity_scores(a['title'])['compound'] for a in articles['articles']]
    return sum(scores) / len(scores) if scores else 0

# 3. Data Preprocessing
eth_data['Returns'] = eth_data['Close'].pct_change()
eth_data['MA_5'] = eth_data['Close'].rolling(5).mean()
eth_data['Target'] = eth_data['Close'].shift(-1) # Predict NEXT hour's price
eth_data = eth_data.dropna()

# 4. Model Training
features = ['Close', 'Volume', 'Returns', 'MA_5']
X = eth_data[features]
y = eth_data['Target']

# Use last 80% for training, 20% for testing
split = int(len(eth_data) * 0.8)
model = RandomForestRegressor(n_estimators=100)
model.fit(X[:split], y[:split])

# 5. Hourly Prediction
current_data = X.tail(1)
predicted_price = model.predict(current_data)[0]

print(f"Current ETH Price: {eth_data['Close'].iloc[-1].item():.2f} EUR")
print(f"Predicted Price for Next Hour: {predicted_price:.2f} EUR")

import yfinance as yf
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

# 1. Fetch Hourly ETH-EUR Data
# We download 1 month of data at 1-hour intervals
ticker = 'ETH-EUR'
df = yf.download(ticker, period='1mo', interval='1h')

# FIX: If yf returns a MultiIndex (common in new versions), flatten it
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

# 2. Feature Engineering
df['Returns'] = df['Close'].pct_change()
df['MA_5'] = df['Close'].rolling(window=5).mean()
df['Target'] = df['Close'].shift(-1)  # We want to predict the NEXT hour
df = df.dropna()

# 3. Prepare Features (X) and Target (y)
features = ['Close', 'Volume', 'Returns', 'MA_5']
X = df[features]
y = df['Target']

# 4. Split and Train (No shuffling for time-series!)
split = int(len(df) * 0.9)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. Get the very latest data point to predict the UPCOMING hour
last_row = X.tail(1)
prediction = model.predict(last_row)[0] # [0] gets the number out of the array
current_price = df['Close'].iloc[-1]    # Using iloc[-1] ensures we get a scalar

print(f"--- Ethereum (ETH-EUR) Hourly Prediction ---")
print(f"Current Price: {current_price:.2f} EUR")
print(f"Predicted Price for Next Hour: {prediction:.2f} EUR")

# Calculate simple Direction
direction = "UP" if prediction > current_price else "DOWN"
print(f"Signal: {direction}")

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

# 1. Fetch Hourly ETH-EUR Data
df = yf.download('ETH-EUR', period='1mo', interval='1h', multi_level_index=False)

# 2. Feature Engineering for Trend Analysis
df['Returns'] = df['Close'].pct_change()
df['MA_20'] = df['Close'].rolling(window=20).mean() # Short-term trend
df['MA_50'] = df['Close'].rolling(window=50).mean() # Medium-term trend
df['Target'] = df['Close'].shift(-1)
df = df.dropna()

# 3. Model Training
features = ['Close', 'Volume', 'Returns', 'MA_20', 'MA_50']
X = df[features]
y = df['Target']

split = int(len(df) * 0.9)
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X[:split], y[:split])

# 4. PREDICTION & CONFIDENCE SCORE
last_row = X.tail(1)
prediction = model.predict(last_row)[0]

# Confidence: Calculate the spread of predictions from all 100 trees
tree_predictions = np.array([tree.predict(last_row.values)[0] for tree in model.estimators_])
std_dev = np.std(tree_predictions)
# Confidence Score (Simplified): 100% minus the relative volatility of predictions
confidence_score = max(0, 100 - (std_dev / prediction * 1000))

# 5. TREND ANALYSIS
current_price = df['Close'].iloc[-1]
ma20 = df['MA_20'].iloc[-1]
ma50 = df['MA_50'].iloc[-1]

if current_price > ma20 > ma50:
    trend = "Strongly Bullish (Uptrend)"
elif current_price < ma20 < ma50:
    trend = "Strongly Bearish (Downtrend)"
else:
    trend = "Neutral / Consolidation"

# 6. RESULTS
print(f"--- Ethereum (ETH-EUR) Hourly Analysis ---")
print(f"Current Price: {current_price:.2f} EUR")
print(f"Predicted Price (1h): {prediction:.2f} EUR")
print(f"Trend Analysis: {trend}")
print(f"Model Confidence Score: {confidence_score:.1f}%")